captainVersion: 4
services:
    # Apache Answer
    $$cap_appname:
        image: apache/answer:$$cap_answer_version
        volumes:
            - $$cap_appname-data:/data
caproverOneClickApp:
    variables:
        - id: $$cap_answer_version
          label: Apache Answer Version
          defaultValue: '1.2.1'
          description: Checkout their docker page for the valid tags https://hub.docker.com/r/apache/answer/tags
          validRegex: /^([^\s^\/])+$/
    instructions:
        start: >-
            A Q&A platform software for teams at any scales. Whether it’s a community forum, help center, or knowledge management platform, you can always count on Answer.
        end: >-
            Aaaand you're done! 😄
            Your service is available at http://$$cap_appname.$$cap_root_domain
    displayName: 'Answer'
    isOfficial: true
    description: Build Q&A Platform with Apache Answer.
    documentation: Taken from https://answer.apache.org/docs
