captainVersion: 4
services:
    $$cap_appname:
        image: lscr.io/linuxserver/emby:$$cap_emby_version
        environment:
            PUID: $$cap_puid
            PGID: $$cap_pgid
            TZ: $$cap_tz
        volumes:
            - $$cap_appname-config:/config
            - $$cap_mediadata:/data
        caproverExtra:
            containerHttpPort: '8096'
caproverOneClickApp:
    variables:
        - id: $$cap_emby_version
          label: Emby Version
          defaultValue: '4.7.14'
          description: Check out their Docker page for the valid tags https://github.com/linuxserver/docker-emby/pkgs/container/emby
          validRegex: /^([^\s^\/])+$/

        - id: $$cap_tz
          label: Time Zone
          defaultValue: Europe/Istanbul
          description: Get yours from https://en.wikipedia.org/wiki/List_of_tz_database_time_zones
          validRegex: /.{1,}/

        - id: $$cap_puid
          label: User ID
          defaultValue: '1000'
          description: User ID that the process uses, run (id $user) in your instance to see the id
          validRegex: /.{1,}/

        - id: $$cap_pgid
          label: Group ID
          defaultValue: '1000'
          description: Group ID that the process uses, run (id $user) in your instance to see the id
          validRegex: /.{1,}/

        - id: $$cap_mediadata
          label: Location of media library on disk
          description: Location of TV and Movies folders on disk.
          defaultValue: '/data/media'
          validRegex: /\/[^\s-][a-zA-Z0-9_\/-]*[^\/][^\s-]/
    instructions:
        start: |-
            Emby organizes video, music, live TV, and photos from personal media libraries and streams them to smart TVs, streaming boxes and mobile devices. This container is packaged as a standalone emby Media Server.

            PS. It might not work with RPi, or atleast, you wont be able to use OpenMax or V4L2 because Caprover ignores 'devices' parameters of docker-compose
        end: |-
            Emby has been successfully deployed! Please wait atleast 2-4 mins before trying to connect. 
            To enable HTTPS, enable it inside app config from caprover dashboard. 'Enable HTTPS' setting inside of Emby might not work.
    displayName: Emby
    isOfficial: true
    description: Emby organizes video, music, live TV, and photos from personal media libraries and streams them to smart TVs, streaming boxes and mobile devices.
    documentation: See https://docs.linuxserver.io/images/docker-emby
