captainVersion: 4
services:
    $$cap_appname:
        image: lscr.io/linuxserver/librespeed:$$cap_librespeed_version
        environment:
            TZ: $$cap_tz
            PUID: $$cap_puid
            PGID: $$cap_guid
            PASSWORD: $$cap_password
        volumes:
            - $$cap_appname-config:/config
caproverOneClickApp:
    variables:
        - id: $$cap_tz
          label: Timezone
          description: This is the timezone for the application, find yours at https://en.wikipedia.org/wiki/List_of_tz_database_time_zones
          defaultValue: Europe/Brussels

        - id: $$cap_librespeed_version
          label: librespeed Version
          defaultValue: 'latest'
          description: Checkout their docker page for the valid tags https://github.com/linuxserver/docker-librespeed/pkgs/container/librespeed
          validRegex: /^([^\s^\/])+$/

        - id: $$cap_puid
          label: User ID
          defaultValue: '1000'
          description: User ID that the process uses, run (id $user) in your instance to see the id
          validRegex: /.{1,}/

        - id: $$cap_guid
          label: Group ID
          defaultValue: '1000'
          description: Group ID that the process uses, run (id $user) in your instance to see the id
          validRegex: /.{1,}/

        - id: $$cap_password
          label: Set the password for the results database.
    instructions:
        start: >-
            Librespeed is a very lightweight Speedtest implemented in Javascript, using XMLHttpRequest and Web Workers. No Flash, No Java, No Websocket, No Bullshit.
        end: >-
            Aaaand you're done! 😄
            Your service is available at http://$$cap_appname.$$cap_root_domain
    displayName: 'Librespeed'
    isOfficial: true
    baseUrl: https://github.com/Fallenbagel/jellyseerr
    description: Librespeed is a very lightweight Speedtest implemented in Javascript, using XMLHttpRequest and Web Workers. No Flash, No Java, No Websocket, No Bullshit.
    documentation: Taken from https://docs.linuxserver.io/images/docker-librespeed
