captainVersion: 4
services:
    $$cap_appname:
        image: ghcr.io/navidrome/navidrome:$$cap_navidrome_version
        volumes:
            - $$cap_appname-data:/data
            - $$cap_music:/music
        caproverExtra:
            containerHttpPort: '4533'
caproverOneClickApp:
    variables:
        - id: $$cap_navidrome_version
          label: Version Tag
          description: Check out their Docker page for the valid tags https://github.com/navidrome/navidrome/pkgs/container/navidrome
          defaultValue: 0.50.2

        - id: $$cap_music
          label: Path to your music folder.
    instructions:
        start: |-
            Navidrome is an open source web-based music collection server and streamer. It gives you freedom to listen to your music collection from any browser or mobile device. It's like your personal Spotify!
        end: |-
            ✅ Navidrome has been deployed!
            --------------------------------------------
            The webui is at http://$$cap_appname.$$cap_root_domain
    displayName: Navidrome
    isOfficial: true
    description: Modern Music Server and Streamer compatible with Subsonic/Airsonic
    documentation: https://www.navidrome.org/docs/installation/docker/
