captainVersion: 4
services:
    # Open wbeui
    $$cap_appname:
        image: ghcr.io/open-webui/open-webui:$$cap_weui_version
        environment:
            OLLAMA_BASE_URL: http://srv-captain--$$cap_appname-api:11434
            WEBUI_SECRET_KEY: $$cap_app_key
        volumes:
            - $$cap_appname-data:/app/backend/data
        caproverExtra:
            containerHttpPort: 8080
    # Ollama
    $$cap_appname-api:
        image: ollama/ollama:$$cap_ollama_version
        volumes:
            - $$cap_appname-api-data:/root/.ollama
        caproverExtra:
            notExposeAsWebApp: 'true'
caproverOneClickApp:
    variables:
        - id: $$cap_weui_version
          label: Open webui Version
          defaultValue: 'v0.3.1'
          description: Checkout their docker page for the valid tags https://github.com/open-webui/open-webui/pkgs/container/open-webui

        - id: $$cap_ollama_version
          label: Ollama Version
          defaultValue: '0.1.42'
          description: Checkout their docker page for the valid tags https://hub.docker.com/r/ollama/ollama/tags

        - id: $$cap_app_key
          label: Secret Key
          description: Secret key.
          defaultValue: $$cap_gen_random_hex(24)
    instructions:
        start: >-
            ChatGPT-Style Web Interface for Ollama 🦙
        end: >-
            Aaaand you're done! 😄
            Your service is available at http://$$cap_appname.$$cap_root_domain
    displayName: 'Open-webui'
    isOfficial: true
    baseUrl: https://github.com/open-webui/open-webui
    description: ChatGPT-Style Web Interface for Ollama 🦙
    documentation: Taken from https://github.com/open-webui/open-webui
