captainVersion: 4
services:
    $$cap_appname:
        image: ghcr.io/rogerfar/rdtclient:$$cap_rdt_version
        volumes:
            - $$cap_appname-db:/data/db
            - $$cap_dl:/data/downloads
        caproverExtra:
            containerHttpPort: 6500
caproverOneClickApp:
    variables:
        - id: $$cap_rdt_version
          label: rdtclient version
          defaultValue: '2.0.61'
          description: Check out their GitHub page for the valid tags https://github.com/rogerfar/rdt-client/pkgs/container/rdtclient
          validRegex: '/.{1,}/'

        - id: $$cap_dl
          label: Download path
          defaultValue: '/data/downloads'
          description: Your local path to download files to
          validRegex: '/.{1,}/'
    instructions:
        start: |-
            This is a web interface to manage your torrents on Real-Debrid, AllDebrid or Premiumize. It supports the following features:

            - Add new torrents through magnets or files
            - Download all files from Real-Debrid, AllDebrid or Premiumize to your local machine automatically
            - Unpack all files when finished downloading
            - Implements a fake qBittorrent API so you can hook up other applications like Sonarr, Radarr or Couchpotato.
        end: |-
            Done! 🚀
    displayName: rdtclient
    isOfficial: true
    description: Real-Debrid Client Proxy
    documentation: Taken from https://github.com/rogerfar/rdt-client
