captainVersion: 4
services:
    # Readeck
    $$cap_appname:
        image: codeberg.org/readeck/readeck:$$cap_readeck_version
        environment:
            READECK_DATABASE_SOURCE: postgres://$$cap_db_user:$$cap_db_pass@srv-captain--$$cap_appname-db:5432/$$cap_db_name
            READECK_LOG_LEVEL: info
            READECK_ALLOWED_HOSTS: $$cap_appname.$$cap_root_domain
            READECK_USE_X_FORWARDED: true
        volumes:
            - $$cap_appname-data:/readeck
        caproverExtra:
            containerHttpPort: 8000
    # Postgres
    $$cap_appname-db:
        image: $$cap_db_version
        environment:
            POSTGRES_USER: $$cap_db_user
            POSTGRES_DB: $$cap_db_name
            POSTGRES_PASSWORD: $$cap_db_pass
        volumes:
            - $$cap_appname-db-data:/var/lib/postgresql/data
        caproverExtra:
            notExposeAsWebApp: 'true'
caproverOneClickApp:
    variables:
        - id: $$cap_readeck_version
          label: Readeck Version
          defaultValue: '0.12.0'
          description: Checkout their docker page for the valid tags https://codeberg.org/readeck/-/packages/container/readeck/versions

        - id: $$cap_db_version
          label: PostgreSQL Version
          defaultValue: 'postgres:16-alpine'
          description: Checkout their docker page for the valid tags https://hub.docker.com/_/postgres

        - id: $$cap_db_user
          label: Postgres database user
          defaultValue: readeck
          description: Enter a user for database

        - id: $$cap_db_name
          label: Postgres database name
          defaultValue: readeck_db
          description: Enter a databse name

        - id: $$cap_db_pass
          label: Postgres database password
          defaultValue: $$cap_gen_random_hex(24)
          description: Enter database password
    instructions:
        start: >-
            Readeck is a simple web application that lets you save the precious readable content of web pages you like and want to keep forever.
        end: >-
            Aaaand you're done! 😄
            Ensure that the PostgreSQL container has fully initialized before restarting the Readeck container to allow it to establish a connection with the database.            Your service is available at http://$$cap_appname.$$cap_root_domain
    displayName: 'Readeck'
    isOfficial: true
    baseUrl: https://codeberg.org/readeck/readeck
    description: See it as a bookmark manager and a read later tool.
    documentation: Taken from https://codeberg.org/readeck/readeck#container
