captainVersion: 4
services:
    $$cap_appname:
        image: searxng/searxng:$$cap_searxng_version
        environment:
            BASE_URL: $$cap_base_url
            INSTANCE_NAME: $$cap_instance_name
        volumes:
            - $$cap_appname-data:/etc/searxng
        caproverExtra:
            containerHttpPort: 8080
caproverOneClickApp:
    variables:
        - id: $$cap_searxng_version
          label: SearXNG Version
          defaultValue: 2023.3.2-abd2d860
          description: Check out their Docker page for the valid tags https://hub.docker.com/r/searxng/searxng/tags
          validRegex: /^([^\s^\/])+$/

        - id: $$cap_base_url
          label: Base url
          description: The base URL of your instance
          defaultValue: http://$$cap_appname.$$cap_root_domain

        - id: $$cap_instance_name
          label: Your instance name
          defaultValue: SearXNG
    instructions:
        start: |-
            SearXNG is a metasearch engine. Users are neither tracked nor profiled.
        end: |-
            Aaaand you're done! 😄
            Your service is available at http://$$cap_appname.$$cap_root_domain
    displayName: SearXNG
    isOfficial: true
    description: Privacy-respecting, hackable metasearch engine
    documentation: https://docs.searxng.org/admin/installation-docker.html
