captainVersion: 4
services:
    $$cap_appname:
        image: zefhemel/silverbullet:$$cap_silverbullet_version
        environment:
            PUID: $$cap_puid
            PGID: $$cap_guid
            SB_USER: $$sb_user:$$sb_pass
            SB_AUTH_TOKEN: $$sb_auth_token
        volumes:
            - $$cap_appname-space:/space
        caproverExtra:
            containerHttpPort: 3000
caproverOneClickApp:
    variables:
        - id: $$cap_silverbullet_version
          label: Version Tag
          description: Check out their Docker page for the valid tags https://hub.docker.com/r/zefhemel/silverbullet/tags
          defaultValue: '0.7.6'

        - id: $$cap_puid
          label: User ID
          defaultValue: '1000'
          description: User ID that the process uses, run (id $user) in your instance to see the id
          validRegex: /.{1,}/

        - id: $$cap_guid
          label: Group ID
          defaultValue: '1000'
          description: Group ID that the process uses, run (id $user) in your instance to see the id
          validRegex: /.{1,}/

        - id: $$sb_auth_token
          label: Auht token
          defaultValue: $$cap_gen_random_hex(24)
          description: 'Enables Authorization: Bearer <token> style authentication on the API (useful for Sync and remote HTTP storage backends.'

        - id: $$sb_user
          label: Username
          defaultValue: tealc
          description: Login Username

        - id: $$sb_pass
          label: Password
          defaultValue: $$cap_gen_random_hex(12)
          description: Login Password
    instructions:
        start: |-
            SilverBullet: A note-taking app tailored for hackers.

            Unlike traditional note apps, it transforms notes into queryable databases, allowing users to build custom knowledge applications.

            It's a hackable notebook for those seeking more than plain text files.
        end: |-
            Aaaand you're done! 😄
            Your service is available at http://$$cap_appname.$$cap_root_domain
    displayName: Siverbullet.md
    isOfficial: true
    description: 'SilverBullet: A note-taking app for hackers that turns notes into queryable databases, enabling custom knowledge applications.'
    documentation: https://silverbullet.md/Install/Docker
