captainVersion: 4
services:
    # Slash
    $$cap_appname:
        image: yourselfhosted/slash:$$cap_slash_version
        volumes:
            - $$cap_appname-data:/var/opt/slash
        caproverExtra:
            containerHttpPort: 5231
caproverOneClickApp:
    variables:
        - id: $$cap_slash_version
          label: Slash Version
          defaultValue: 0.5.0
          description: Check out their Docker page for the valid tags https://hub.docker.com/r/yourselfhosted/slash/tags
    instructions:
        start: |-
            Slash is an open source, self-hosted bookmarks and link sharing platform. 
            It allows you to organize your links with tags, and share them with custom shortened URLs. 
            Slash also supports team sharing of link libraries for easy collaboration.
        end: >-
            Slash has been successfully deployed!
            You can access the application at `http://$$cap_appname.$$cap_root_domain`.
    displayName: Slash
    isOfficial: true
    description: An open source, self-hosted bookmarks and link sharing platform. Save and share your links very easily
    documentation: Taken from https://github.com/boojack/slash
