captainVersion: 4
services:
    # Trilium
    $$cap_appname:
        image: zadam/trilium:$$cap_trilium_version
        environment:
            TRILIUM_DATA_DIR: /home/node/trilium-data
        volumes:
            - $$cap_appname-data:/home/node/trilium-data
        caproverExtra:
            containerHttpPort: '8080'
caproverOneClickApp:
    variables:
        - id: $$cap_trilium_version
          label: Trilium Version
          defaultValue: '0.59.3'
          description: https://hub.docker.com/r/zadam/trilium/tags
          validRegex: /^([^\s^\/])+$/
    instructions:
        start: >-
            Trilium Notes is a hierarchical note taking application with focus on building large personal knowledge bases.
        end: >-
            Aaaand you're done! 😄
            Your service is available at http://$$cap_appname.$$cap_root_domain
    displayName: Trilium
    isOfficial: true
    baseUrl: https://github.com/zadam/trilium
    description: Build your personal knowledge base with Trilium Notes
    documentation: Taken from https://github.com/zadam/trilium
