captainVersion: 4
services:
    $$cap_appname:
        image: bsyed/troddit:$$cap_troddit_version
        environment:
            CLIENT_ID: $$cap_client_id
            CLIENT_SECRET: $$cap_client_secret
            REDDIT_REDIRECT: $$cap_redirect_url
            NEXTAUTH_SECRET: $$cap_gen_random_hex(16)
            NEXTAUTH_URL: $$cap_app_url
        caproverExtra:
            containerHttpPort: 3000
caproverOneClickApp:
    variables:
        - id: $$cap_troddit_version
          label: Troddit Version
          defaultValue: 'latest'
          description: Checkout their docker page for the valid tags https://hub.docker.com/r/bsyed/troddit/tags
          validRegex: /^([^\s^\/])+$/

        - id: $$cap_app_url
          label: Base url.
          defaultValue: https://$$cap_appname.$$cap_root_domain

        - id: $$cap_redirect_url
          label: Reddit redirect url.
          defaultValue: https://$$cap_appname.$$cap_root_domain/api/auth/callback/reddit

        - id: $$cap_client_id
          label: ID of your Reddit app

        - id: $$cap_client_secret
          label: Secret from your Reddit app
    instructions:
        start: >-
            Troddit is a web app for Reddit. Follow subreddits and users locally or login with your Reddit account to vote, comment, and manage your existing subscriptions.
        end: >-
            Aaaand you're done! 😄
            Your service is available at https://$$cap_appname.$$cap_root_domain
    displayName: Troddit
    isOfficial: true
    description: A web client for Reddit with authenticated logins and a variety of browsing options.
    documentation: https://github.com/burhan-syed/troddit
