captainVersion: 4
services:
    # vikunja Frontend
    $$cap_appname:
        image: vikunja/frontend:$$cap_vikunja_frontend_version
        environment:
            VIKUNJA_API_URL: https://$$cap_appname-api.$$cap_root_domain/api/v1

    # vikunja Api (Backend)
    $$cap_appname-api:
        image: vikunja/api:$$cap_vikunja_api_version
        environment:
            VIKUNJA_DATABASE_HOST: srv-captain--$$cap_appname-mariadb
            VIKUNJA_DATABASE_USER: $$cap_mariadb-user
            VIKUNJA_DATABASE_PASSWORD: $$cap_mariadb-pass
            VIKUNJA_DATABASE_TYPE: mysql
            VIKUNJA_DATABASE_DATABASE: $$cap_mariadb-db
            VIKUNJA_SERVICE_JWTSECRET: $$cap_jwt_secret
            VIKUNJA_SERVICE_FRONTENDURL: https://$$cap_appname.$$cap_root_domain/
        volumes:
            - $$cap_appname-api-files:/app/vikunja/files
        caproverExtra:
            containerHttpPort: 3456

    # MariaDB
    $$cap_appname-mariadb:
        image: mariadb:$$cap_mariadb_version
        environment:
            MYSQL_RANDOM_ROOT_PASSWORD: '1'
            MYSQL_DATABASE: $$cap_mariadb-db
            MYSQL_USER: $$cap_mariadb-user
            MYSQL_PASSWORD: $$cap_mariadb-pass
        volumes:
            - $$cap_appname-mariadb-data:/var/lib/mysql
        caproverExtra:
            notExposeAsWebApp: 'true'
caproverOneClickApp:
    variables:
        - id: $$cap_vikunja_frontend_version
          label: Vikunja frontend Version Tag
          description: Check out their Docker page for the valid tags https://hub.docker.com/r/vikunja/frontend/tags
          defaultValue: '0.21.0'

        - id: $$cap_vikunja_api_version
          label: Vikunja backend Version Tag
          description: Check out their Docker page for the valid tags https://hub.docker.com/r/vikunja/api/tags
          defaultValue: '0.21.0'

        - id: $$cap_mariadb_version
          label: MariaDB Version
          defaultValue: '11.2.2'
          description: Checkout their docker page for the valid tags https://hub.docker.com/r/library/mariadb/tags/
          validRegex: /^([^\s^\/])+$/

        - id: $$cap_jwt_secret
          label: Secret for JWT tokens. This should be a long random string.
          defaultValue: $$cap_gen_random_hex(24)
          description: JWT secret token

        - id: $$cap_mariadb-db
          label: MariaDB Database
          description: Database name for Chevereto
          defaultValue: 'Vikunja'

        - id: $$cap_mariadb-user
          label: MariaDB User
          description: Database User for Chevereto
          defaultValue: 'Vikunja'

        - id: $$cap_mariadb-pass
          label: MariaDB database user password
          defaultValue: $$cap_gen_random_hex(16)
          description: Super secret database user password
    instructions:
        start: |-
            The open-source, self-hostable to-do app. Organize everything, on all platforms.
        end: |-
            Aaaand you're done! 😄

            Don't forget to enable HTTPS inside app config from caprover for the frontend en api
    displayName: Vikunja
    isOfficial: true
    description: The open-source, self-hostable to-do app. Organize everything, on all platforms.
    documentation: https://vikunja.io/docs/
