captainVersion: 4
services:
    # Wiki:js
    $$cap_appname:
        image: ghcr.io/requarks/wiki:$$cap_wikijs_version
        environment:
            NEXTAUTH_SECRET: $$cap_app_key
            NEXTAUTH_URL: https://$$cap_appname.$$cap_root_domain
            DB_TYPE: postgres
            DB_HOST: srv-captain--$$cap_appname-db
            DB_PORT: 5432
            DB_USER: $$cap_db_user
            DB_PASS: $$cap_db_pass
            DB_NAME: $$cap_db_name
        volumes:
            - $$cap_appname-config:/config
            - $$cap_appname-data:/data
        caproverExtra:
            containerHttpPort: 3000
    # Postgres
    $$cap_appname-db:
        image: postgres:12-alpine
        environment:
            POSTGRES_USER: $$cap_db_user
            POSTGRES_DB: $$cap_db_name
            POSTGRES_PASSWORD: $$cap_db_pass
        volumes:
            - $$cap_appname-db-data:/var/lib/postgresql/data
        caproverExtra:
            notExposeAsWebApp: 'true'
caproverOneClickApp:
    variables:
        - id: $$cap_wikijs_version
          label: Wiki.JS Version
          defaultValue: 2
          description: Checkout their docker page for the valid tags https://github.com/Requarks/wiki/pkgs/container/wiki

        - id: $$cap_db_user
          label: Postgres database user
          defaultValue: wikijs
          description: Enter a user for database

        - id: $$cap_db_name
          label: Postgres database name
          defaultValue: wikijs_db
          description: Enter a databse name

        - id: $$cap_db_pass
          label: Postgres database password
          defaultValue: $$cap_gen_random_hex(24)
          description: Enter database password
    instructions:
        start: >-
            Make documentation a joy to write using Wiki.js's beautiful and intuitive interface!
        end: >-
            Aaaand you're done! 😄
            Your service is available at https://$$cap_appname.$$cap_root_domain
    displayName: 'Wiki.js'
    isOfficial: true
    description: The most powerful and extensible open source Wiki software
    documentation: Taken from https://js.wiki
