captainVersion: 4
services:
    # Wizarr
    $$cap_appname:
        image: ghcr.io/wizarrrr/wizarr:$$cap_wizarr_version
        volumes:
            - $$cap_appname-database:/data/database
        caproverExtra:
            containerHttpPort: '5690'
caproverOneClickApp:
    variables:
        - id: $$cap_wizarr_version
          label: Wizarr Version
          defaultValue: '3.5.1'
          description: Checkout their docker page for the valid tags https://github.com/wizarrrr/wizarr/pkgs/container/wizarr
          validRegex: /^([^\s^\/])+$/
    instructions:
        start: >-
            Wizarr is an advanced user invitation and management system for Jellyfin, Plex, Emby etc.
        end: >-
            Aaaand you're done! 😄
            Your service is available at http://$$cap_appname.$$cap_root_domain
    displayName: 'Wizarr'
    isOfficial: true
    description: Wizarr is an advanced user invitation and management system for Jellyfin, Plex, Emby etc.
    documentation: Taken from https://docs.wizarr.dev/
