captainVersion: 4
services:
    # yt-dlp-web
    $$cap_appname:
        image: sooros5132/yt-dlp-web:$$cap_yt-dlp-web_version
        volumes:
            - $$cap_appname-downloads:/downloads
            - $$cap_appname-cache:/cache
        caproverExtra:
            containerHttpPort: 3000
caproverOneClickApp:
    variables:
        - id: $$cap_yt-dlp-web_version
          label: yt-dlp-web Version
          defaultValue: '0.2.23'
          description: Checkout their docker page for the valid tags https://hub.docker.com/r/sooros5132/yt-dlp-web/tags
    instructions:
        start: >-
            Self-hosted yt-dlp with the Web UI.
        end: >-
            Aaaand you're done! 😄
            Your service is available at http://$$cap_appname.$$cap_root_domain
    displayName: 'yt-dlp-web'
    isOfficial: true
    baseUrl: https://github.com/sooros5132/yt-dlp-web
    description: Self-hosted yt-dlp with the Web UI. You can watch or download videos downloaded to a remote server.
    documentation: Taken from https://github.com/sooros5132/yt-dlp-web
